[package]
name = "platypos_slab"
version = "0.1.0"
edition = "2021"
description = "Lock-free concurrent slab for PlatypOS"

[dependencies]
modular-bitfield = "0.11.2"
platypos_hal = { path = "../hal" }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5", features = ["checkpoint"] }
