[workspace]
members = [
    "slog_kernel",
    "x86_64_ext",

    "pos_cli",
    "pal",
    "kernel",
    "kernel_x86_64",
    "kernel_x86_64/boot_info",
    "loader_uefi"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"