cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = ["kernel", "ktest", "ktest/macros", "xtask"]

# [profile.dev]
# # For backtraces
# rustflags = ["-Cforce-frame-pointers"]

# [profile.release]
# lto = "thin"
# debug = true
# split-debuginfo = "packed"
