[workspace]
members = [
	"kernel",
	"apic",
	"kutil",
	"serial_logger",

    "platypos_config",
	"platypos_kernel",
	"platypos_test",
	"platypos_test/macro"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
