[workspace]
members = [
	"apic",
	"serial_logger",

    "platypos_loader",
    "platypos_config",
	"platypos_kernel",
	"platypos_test",
	"platypos_test/macro",
	"platypos_runner",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
