cargo-features = ["profile-rustflags"]

[workspace]
members = ["kernel", "xtask"]

# [profile.dev]
# # For backtraces
# rustflags = ["-Cforce-frame-pointers"]

# [profile.release]
# lto = "thin"
# debug = true
# split-debuginfo = "packed"
