[config]
skip_core_tasks = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.build]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xbuild", "--target", "${TARGET}"]

[tasks.build_all]
workspace = false
run_task = { name = "build", fork = true }

[tasks.run]
dependencies = [ "build_all" ]
workspace = false
command = "./scripts/launch.sh"

[tasks.install_tools]
workspace = false
script = ['''
# TODO: support more than just Arch
sudo pacman -Syu gdb qemu ovmf socat
''']
