[package]
name = "platypos_kernel"
version = "0.1.0"
edition = "2021"
description = "Core PlatypOS kernel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.0"
bitvec = { version = "1.0.0", features = ["atomic"], default-features = false }
embedded-graphics = "0.7.1"
itertools = { version = "0.10.3", default-features = false }
log = { version = "0.4.16", features = [
    "kv_unstable",
    "kv_unstable_sval",
    "max_level_trace",
    "release_max_level_debug",
], default-features = false }
spin = { version = "0.9.2", features = ["mutex", "once"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.10.12"
uart_16550 = "0.2.17"
x86_64 = "0.14.8"
