[package]
name = "kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
acpi = { git = "https://github.com/bnavetta/acpi.git" }
apic = { path = "../apic" }
kutil = { path = "../kutil" }
serial_logger = { path = "../serial_logger" }
array-init = "~0.0.4"
bit_field = "~0.10.0"
log = "~0.4.6"
phf = { version = "~0.7.24", features = ["core"] }
pic8259_simple = "~0.1.1"
raw-cpuid = "~6.1"
spin = "~0.5"
volatile = "~0.2.6"
x86_64 = "~0.7"

[dependencies.bootloader]
version = "~0.6"
features = ["map_physical_memory"]

[dependencies.crossbeam-utils]
version = "~0.6.5"
default-features = false
features = ["nightly"]

[dependencies.hashbrown]
version = "0.4.0"
features = ["nightly"]

[dependencies.intrusive-collections]
version = "~0.7.8"
default-features = false
features = ["nightly"]

[dependencies.lazy_static]
version = "~1.3.0"
default-features = false
features = ["spin_no_std"]

[dependencies.ux]
version = "~0.1.3"
default-features = false

[build-dependencies]
toml = "~0.5"
phf_codegen = "~0.7.24"

[package.metadata.bootimage]
default-target = "x86_64-os.json"
#run-args = ["-cpu", "max", "-d", "unimp,guest_errors,int,cpu_reset,trace:pic_interrupt,trace:pic_update_irq,trace:pic_set_irq,trace:apic_deliver_irq,trace:apic_local_deliver", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
run-args = ["-machine", "q35", "-cpu", "max", "-smp", "cores=2", "-d", "unimp,guest_errors,int,cpu_reset", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
#run-args = ["-machine", "q35", "-cpu", "max", "-d", "unimp,guest_errors,int,cpu_reset,trace:pic_interrupt", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
#run-args = ["-cpu", "max", "-smp", "cores=4", "-d", "int,cpu_reset", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
#run-args = ["-accel", "hvf", "-cpu", "host,migratable=no", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
#run-args = ["-machine", "accel=kvm", "-cpu", "host,migratable=no", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
test-args = ["-cpu", "max", "-smp", "cores=4", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
test-success-exit-code = 33         # (0x10 << 1) | 1
