[package]
name = "platypos_kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.7.2", default-features = false, features = ["compile-time-rng"] }
ansi_rgb = "0.2.0"
arrayvec = { version = "0.5.2", default-features = false, features = ["unstable-const-fn"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
paste = "1.0.4"
platypos_boot_info = { path = "../boot_info" }
spinning_top = { version = "0.2.2", features = ["nightly"] }
tracing = { git = "https://github.com/tokio-rs/tracing", default-features = false, features = ["attributes"] }
tracing-core = { git = "https://github.com/tokio-rs/tracing", default-features = false }
uart_16550 = { version = "0.2.12", features = ["nightly"] }
x86_64 = "0.13.2"

[features]
gdb = []
