[package]
name = "kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
kutil = { path = "../kutil" }
serial_logger = { path = "../serial_logger" }
bit_field = "~0.9.0"
log = "~0.4.6"
raw-cpuid = "~6.1"
spin = "~0.5"
x86_64 = "~0.3"

[dependencies.bootloader]
version = "~0.6"
features = ["map_physical_memory"]

# AtomicCell might be useful
#[dependencies.crossbeam-utils]
#version = "~0.6.5"
#default-features = false
#features = ["nightly"]

[dependencies.intrusive-collections]
version = "~0.7.8"
default-features = false
features = ["nightly"]

[package.metadata.bootimage]
default-target = "x86_64-os.json"
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]
test-success-exit-code = 33         # (0x10 << 1) | 1
