[package]
name = "kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]

[dependencies]
dbg = { path = "../dbg" }
bootloader_precompiled = "0.2.0"

[package.metadata.bootimage]
default-target = "x86_64-os.json"