[package]
name = "platypos_kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_rgb = "0.2.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
paste = "1.0.4"
riscv = { git = "https://github.com/rust-embedded/riscv.git", rev = "be2927e248c11bb3c745f01162ba8828a79ec569" }
# spinning_top = { version = "0.2.4", features = ["nightly"] }

[dependencies.fdt-rs]
version = "0.4"
default-features = false