[package]
name = "kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
dbg = { path = "../dbg" }
kutil = { path = "../kutil" }
bootloader_precompiled = "~0.3"
raw-cpuid = "~6.1"
x86_64 = "~0.3"

[package.metadata.bootimage]
default-target = "x86_64-os.json"