[package]
name = "kernel"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
kutil = { path = "../kutil" }
serial_logger = { path = "../serial_logger" }
log = "~0.4.6"
bootloader = "~0.6"
raw-cpuid = "~6.1"
x86_64 = "~0.3"

[package.metadata.bootimage]
default-target = "x86_64-os.json"