[package]
name = "platypos_kernel"
version = "0.1.0"
edition = "2021"
description = "Core PlatypOS kernel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.0"
embedded-graphics = "0.7.1"
log = { version = "0.4.16", features = [
    "kv_unstable",
    "kv_unstable_sval",
    "max_level_trace",
    "release_max_level_debug",
], default-features = false }
platypos_platform = { path = "../platform" }
spin = { version = "0.9.2", features = ["mutex", "once"] }
