[package]
name = "kernel_x86_64"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
description = "PlatypOS Kernel for the x86-64 platform"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
hal = { path = "../hal" }
serial_logger = { path = "../serial_logger" }

bit_field = "0.10"
bootloader = { version = "0.6", features = ["map_physical_memory"] }
intrusive-collections = { version = "0.7", default-features = false, features = ["nightly"] }
log = "0.4"
spin = "0.5"
x86_64 = "0.7"

[package.metadata.bootimage]
default-target = "x86_64-os.json"
run-args = ["-machine", "q35", "-cpu", "max", "-smp", "cores=2", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "mon:stdio"]