[package]
name = "apic"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
x86_64 = "~0.7.0"
bit_field = "~0.10.0"
raw-cpuid = "~6.1"
spin = "~0.5"
log = "~0.4.6"
