[package]
name = "ktest"
version = "0.1.0"
edition = "2021"
description = "Kernel unit test harness"

[dependencies]
linkme = "0.3"
qemu-exit = "3.0"
tracing = { version = "0.1", default-features = false }
ktest_macros = { path = "./macros" }
