[package]
name = "platypos_pal"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"

[dependencies.arrayvec]
version = "0.5"
default-features = false