[package]
name = "pos_cli"
version = "0.1.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[dependencies]
clap-verbosity-flag = "0.3"
eyre = "0.6"
log = "0.4"
pretty_env_logger = "0.4"
structopt = "0.3"
tempfile = "3.1"