#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import getpass
import subprocess

import click


def exec_command(args, cwd=None):
    try:
        return subprocess.call(args, cwd=cwd)
    except Exception as ex:
        click.echo(u"❌ Running " + click.style(" ".join(args), fg="red") + " failed", err=True)
        click.secho(str(ex), fg="red", err=True)
        return 1


@click.group()
def pos():
    """
    Command line tool for platypos
    """
    pass


@pos.command()
def prereqs():
    exec_command(['cargo', 'install', 'bootimage', 'cargo-xbuild', '--force'])
    exec_command(['rustup', 'component', 'add', 'rust-src'])
    exec_command(['rustup', 'component', 'add', 'llvm-tools-preview'])


@pos.command()
def build():
    exec_command(["bootimage", "build", "--manifest-path", "platypos_x86_64/Cargo.toml"])


@pos.command()
@click.option('--debug/--no-debug', default=False)
def run(debug):
    click.secho(u"🏃‍ Running in QEMU", fg="blue")
    args = ['cargo', 'xrun']

    if debug:
        args.extend(['--', '-s', '-S'])

    # xrun doesn't seem to work with -p
    exec_command(args, cwd="platypos_x86_64")


@pos.command()
def test():
    click.secho("Testing kernel", fg="blue")
    exec_command(["cargo", "xtest"], cwd="platypos_kernel")


if __name__ == '__main__':
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    os.chdir(root)
    pos()
