[package]
name = "platypos_boot_info"
version = "0.0.1"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
description = "Shared types for passing information from the bootloader to the kernel"
edition = "2018"

[dependencies]
x86_64 = "0.10"
x86_64_ext = { path = "../x86_64_ext" }
