[alias]
tt = "-q test --target thumbv7m-none-eabi --test"
rb = "-q run --target thumbv7m-none-eabi --bin"
rrb = "-q run --target thumbv7m-none-eabi --release --bin"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
runner = "cargo -q run --manifest-path ../../qemu-run/Cargo.toml"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",

  # CI cannot set this, so we do it here
  "-Dwarnings",
]
